config/routes.rb
Rails.application.routes.draw do
  get 'welcome/logout'

  get 'mail/index'

  resources :projects
  resources :billablehours
  resources :billablehours
  resources :projects
  resources :businesses
  resources :billablehours
  resources :billablehours
  resources :businesses
  resources :businesses
  resources :billable_hours
  resources :businesses
  resources :billable_hours
  resources :projects
  resources :businesses
  resources :projects
  resources :billable_hours
  get 'login/signin'

  get 'welcome/index'

  resources :users

  root 'welcome#index'

end

app/models/billablehour.rb
class Billablehour < ActiveRecord::Base
	has_many :projects
end

app/controllers/billablehours_controller.rb
class BillablehoursController < ApplicationController
  before_action :set_billablehour, only: [:show, :edit, :update, :destroy]
  # GET /billablehours
  # GET /billablehours.json
  def index
    @project_id = params[:project_id]
    @user = User.find_by_id(session[:user_id])
    if(@user.id && @user.id !="5") 
      @billablehours = Billablehour.joins("LEFT JOIN projects b on b.id = billablehours.project_id").where("billablehours.user_id=#{@user.id} AND billablehours.project_id = #{@project_id} AND billablehours.paid IS NULL").all.select("billablehours.*, b.project_name")
    else
      @billablehours = Billablehour.all
    end
  end

  # GET /billablehours/1
  # GET /billablehours/1.json
  def show
  end

  # GET /billablehours/new
  def new
    @billablehour = Billablehour.new
    @user = User.find_by_id(session[:user_id])
    @projects = Project.all.where("user_id=#{@user.id}").order(project_name: :asc)  #Records those has a content
    @project_id = params[:project_id]
  end

  # GET /billablehours/1/edit
  def edit
    @user = User.find_by_id(session[:user_id])
    @projects = Project.all.where("user_id=#{@user.id}").order(project_name: :asc)  #Records those has a content
  end

  # POST /billablehours
  # POST /billablehours.json
  def create
    @billablehour = Billablehour.new(billablehour_params)

    respond_to do |format|
      if @billablehour.save
        format.html { redirect_to "/" }
        format.json { render :show, status: :created, location: @billablehour }
      else
        format.html { render :new }
        format.json { render json: @billablehour.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /billablehours/1
  # PATCH/PUT /billablehours/1.json
  def update
    respond_to do |format|
      if @billablehour.update(billablehour_params)
        format.html { redirect_to @billablehour, notice: 'Billablehour was successfully updated.' }
        format.json { render :show, status: :ok, location: @billablehour }
      else
        format.html { render :edit }
        format.json { render json: @billablehour.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /billablehours/1
  # DELETE /billablehours/1.json
  def destroy
    @billablehour.destroy
    respond_to do |format|
      format.html { redirect_to billablehours_url, notice: 'Billablehour was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_billablehour
      @billablehour = Billablehour.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def billablehour_params
      params.require(:billablehour).permit(:project_id, :business_id, :user_id, :hours, :start_time, :end_time, :timestamp)
    end
end

app/helpers/billable_hours_helper.rb
module BillableHoursHelper
end

app/helpers/billablehours_helper.rb
module BillablehoursHelper
end

app/views/billablehours/_form.html.erb
<%= form_for(@billablehour) do |f| %>
  <% if @billablehour.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@billablehour.errors.count, "error") %> prohibited this billablehour from being saved:</h2>

      <ul>
      <% @billablehour.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.collection_select(:project_id, @projects.all, :id, :project_name, {:selected => @project_id}) %>


  <div class="field">
    <%= f.label :hours %><br>
    <%= f.text_field :hours %>
  </div>
  <div class="field">
    <%= f.label :start_time %><br>
    <%= f.date_select :start_time %>
  </div>
  <%= f.hidden_field :user_id, :value => session[:user_id] %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/billablehours/edit.html.erb
<h1>Editing Billablehour</h1>

<%= render 'form' %>

<%= link_to 'Show', @billablehour %> |
<%= link_to 'Back', billablehours_path %>

app/views/billablehours/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Billablehours</h1>

<table border=1>
  <thead>
    <tr>
      <th>Project</th>
      <th>User</th>
      <th>Hours</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @billablehours.each do |billablehour| %>
      <tr>
        <td><%= billablehour.project_name %></td>
        <td><%= @user.first_name %></td>
        <td><%= billablehour.hours %></td>
        <td><%= billablehour.start_time %></td>
        <td><%= link_to 'Show', billablehour %>
        <%= link_to 'Edit', edit_billablehour_path(billablehour) %>
        <%= link_to 'Destroy', billablehour, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Billablehour', new_billablehour_path %>

app/views/billablehours/new.html.erb
<h1>New Billablehour</h1>

<%= render 'form' %>

<%= link_to 'Back', billablehours_path %>

app/views/billablehours/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Project:</strong>
  <%= @billablehour.project_id %>
</p>

<p>
  <strong>Business:</strong>
  <%= @billablehour.business_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @billablehour.user_id %>
</p>

<p>
  <strong>Hours:</strong>
  <%= @billablehour.hours %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @billablehour.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @billablehour.end_time %>
</p>

<p>
  <strong>Timestamp:</strong>
  <%= @billablehour.timestamp %>
</p>

<%= link_to 'Edit', edit_billablehour_path(@billablehour) %> |
<%= link_to 'Back', billablehours_path %>