config/routes.rb
Rails.application.routes.draw do
  get 'welcome/logout'

  get 'mail/index'

  resources :projects
  resources :billablehours
  resources :billablehours
  resources :projects
  resources :businesses
  resources :billablehours
  resources :billablehours
  resources :businesses
  resources :businesses
  resources :billable_hours
  resources :businesses
  resources :billable_hours
  resources :projects
  resources :businesses
  resources :projects
  resources :billable_hours
  get 'login/signin'

  get 'welcome/index'

  resources :users

  root 'welcome#index'

end

app/models/project.rb
class Project < ActiveRecord::Base
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:project_name, :user_id, :business_id, :budget, :start_time, :end_time, :timestamp)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :project_name %><br>
    <%= f.text_field :project_name %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :business_id %><br>
    <%= f.number_field :business_id %>
  </div>
  <div class="field">
    <%= f.label :budget %><br>
    <%= f.text_field :budget %>
  </div>
  <div class="field">
    <%= f.label :start_time %><br>
    <%= f.datetime_select :start_time %>
  </div>
  <div class="field">
    <%= f.label :end_time %><br>
    <%= f.datetime_select :end_time %>
  </div>
  <div class="field">
    <%= f.label :timestamp %><br>
    <%= f.datetime_select :timestamp %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Projects</h1>

<table>
  <thead>
    <tr>
      <th>Project name</th>
      <th>User</th>
      <th>Business</th>
      <th>Budget</th>
      <th>Start time</th>
      <th>End time</th>
      <th>Timestamp</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.project_name %></td>
        <td><%= project.user_id %></td>
        <td><%= project.business_id %></td>
        <td><%= project.budget %></td>
        <td><%= project.start_time %></td>
        <td><%= project.end_time %></td>
        <td><%= project.timestamp %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Project name:</strong>
  <%= @project.project_name %>
</p>

<p>
  <strong>User:</strong>
  <%= @project.user_id %>
</p>

<p>
  <strong>Business:</strong>
  <%= @project.business_id %>
</p>

<p>
  <strong>Budget:</strong>
  <%= @project.budget %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @project.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @project.end_time %>
</p>

<p>
  <strong>Timestamp:</strong>
  <%= @project.timestamp %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>